module.exports = {
  pos: [
    {
        MID: '416696',
        TID: '16885527',
        MCC_CDE: '2741',
        M_NAME: 'S Dining & Sweets',
        MCC_DSC: 'Dining',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2NQ',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    }, 
    {
        MID: '416697',
        TID: '16885532',
        MCC_CDE: '2741',
        M_NAME: 'D Garments',
        MCC_DSC: 'Cloths',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2NQ',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    }, 
    {
        MID: '416694',
        TID: '16885537',
        MCC_CDE: '2741',
        M_NAME: 'Stuart Travels',
        MCC_DSC: 'Travel',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2NL',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    }, 
    {
        MID: '416695',
        TID: '16885542',
        MCC_CDE: '2741',
        M_NAME: 'Mike Electronics',
        MCC_DSC: 'Electronics',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2NJ',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },
    {
        MID: '416698',
        TID: '16885547',
        MCC_CDE: '2741',
        M_NAME: 'S Dining & Snaks',
        MCC_DSC: 'Dining',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2PE',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },
    {
        MID: '416699',
        TID: '16885567',
        MCC_CDE: '2741',
        M_NAME: 'David Garments',
        MCC_DSC: 'Cloths',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2NL',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },
    {
        MID: '416704',
        TID: '16885573',
        MCC_CDE: '2741',
        M_NAME: 'Peter Travels',
        MCC_DSC: 'Travel',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2NN',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },
    {
        MID: '416703',
        TID: '16885575',
        MCC_CDE: '2338',
        M_NAME: 'Indian Dining',
        MCC_DSC: 'Dining',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2NG',
        PREMISE_NUM: '',
        PREMISE_NME: 'PALM HILLS',
        STREET_NUM: '42',
        STREET_NME: 'ORCHARD LN',
        DISTRICT_NME: '',
        CITY_NME: 'SOUTHAMPTON'
    },
    {
        MID: '416703',
        TID: '16885575',
        MCC_CDE: '2338',
        M_NAME: 'Inetrnational Dining',
        MCC_DSC: 'Dining',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2NQ',
        PREMISE_NUM: '',
        PREMISE_NME: 'PALM HILLS',
        STREET_NUM: '42',
        STREET_NME: 'ORCHARD LN',
        DISTRICT_NME: '',
        CITY_NME: 'SOUTHAMPTON'
    },
    {
        MID: '416703',
        TID: '16885575',
        MCC_CDE: '2338',
        M_NAME: 'India house',
        MCC_DSC: 'Dining',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2PX',
        PREMISE_NUM: '',
        PREMISE_NME: 'PALM HILLS',
        STREET_NUM: '42',
        STREET_NME: 'ORCHARD LN',
        DISTRICT_NME: '',
        CITY_NME: 'SOUTHAMPTON'
    },
    {
        MID: '416703',
        TID: '16885575',
        MCC_CDE: '2338',
        M_NAME: 'Asian Rest',
        MCC_DSC: 'Dining',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2LP',
        PREMISE_NUM: '',
        PREMISE_NME: 'PALM HILLS',
        STREET_NUM: '42',
        STREET_NME: 'ORCHARD LN',
        DISTRICT_NME: '',
        CITY_NME: 'SOUTHAMPTON'
    },
    {
        MID: '416708',
        TID: '16885589',
        MCC_CDE: '2338',
        M_NAME: 'Indian Garments',
        MCC_DSC: 'Cloths',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2NW',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },

    {
        MID: '416709',
        TID: '16885591',
        MCC_CDE: '2339',
        M_NAME: 'new India Garments',
        MCC_DSC: 'Cloths',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2PU',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },

    {
        MID: '416709',
        TID: '16885591',
        MCC_CDE: '2339',
        M_NAME: 'new England Garments',
        MCC_DSC: 'Cloths',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2LR',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },
    {
        MID: '416704',
        TID: '16885573',
        MCC_CDE: '2741',
        M_NAME: 'Indian Travels',
        MCC_DSC: 'Travel',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2EH',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },
    {
        MID: '416704',
        TID: '16885573',
        MCC_CDE: '2741',
        M_NAME: 'International Travels',
        MCC_DSC: 'Travel',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2LW',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },

    {
        MID: '416704',
        TID: '16885573',
        MCC_CDE: '2741',
        M_NAME: 'International Travels',
        MCC_DSC: 'Travel',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2LS',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },
    {
        MID: '416695',
        TID: '16885542',
        MCC_CDE: '2741',
        M_NAME: 'A Electronics',
        MCC_DSC: 'Electronics',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2PE',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },
    {
        MID: '416695',
        TID: '16885542',
        MCC_CDE: '2741',
        M_NAME: 'Eng Electronics',
        MCC_DSC: 'Electronics',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2LG',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },
    {
        MID: '416695',
        TID: '16885542',
        MCC_CDE: '2741',
        M_NAME: 'ABB Electronics',
        MCC_DSC: 'Electronics',
        OUTER_POSTAL_CODE: 'SW15',
        INNER_POSTAL_CODE: '2PU',
        PREMISE_NUM: '',
        PREMISE_NME: 'COTTESBROOKE PARK',
        STREET_NUM: '148',
        STREET_NME: 'PUTNEY BRIDGE RD',
        DISTRICT_NME: '',
        CITY_NME: 'LONDON'
    },
],
}